### ISSUE TITLE
Error on screen when playing a Youtube playlist

### ISSUE THREAD

**Issue by acca** [Kolifanes/plugin.video.youtube#112]
I'm using addon 5.2.1 on OSMC. When I try to send a Youtube playlist link (via Yatse sharing) from my mobile phone to the media center the following happen:

1. Playlist videos start playing
2. An error message, saying "Playing error" appear on the screen and it is not possible to remove without stop the video.
3. On log I can see this line:
`ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?playlist_id=RDLdRxXID_b28&order=default&play=1&video_id=LdRxXID_b28]`

Since playlist starts normally how is it possible to remove this strange error message ?

**Comment by acca** [comment]
Seems that adding this:

```
<advancedsettings>
  <playlisttimeout>40</playlisttimeout> 
</advancedsettings>
```

or another higher value in `/home/osmc/.kodi/userdata/advancedsettings.xml` solves the problem which is probably related to the low performances of my RPi, see:https://github.com/maxgalbu/xbmc.plugin.video.nba/blob/master/docs/bug_description.one_or_more_items_failed_to_play.md.

I'm going to test it a bit, then I will close the issue.

**Comment by hrmeetsingh** [comment]
Hi, did it work for you? I am getting a similar error message while searching a video. Running OSMC on pi 3 model b.

**Comment by acca** [comment]
Yes it worked. Of course was about a year ago and I did many OSMC updates in the meantime. Anyway yeah it should work, give it a try.
