### ISSUE TITLE
Unpausing a video after a long pause cause play to freeze and then stop

### ISSUE THREAD

**Issue by andersea** [Kolifanes/plugin.video.youtube#117]
You cannot pause a video for more that a couple of minutes, because otherwise when you unpause it, the video freezes and eventually you drop back to Kodi menu.

Steps to reproduce:

Play a long video.
Pause it for 10 minutes.
Unpause it.

Expected behaviour:

Video continues playing without any problems after pausing indefinitely. (Unless the video is no longer available or some catastrophic event has occured.)

Actual behaviour:

After unpausing, the video plays for a short time, then it freezes and a short while later you drop out into the menu you where in before you started playing the video.

This has been a problem since all the time I have been using Kodi on different versions of ubuntu. Right now my config is:

Lubuntu 16.04.1 LTS, with mainline kernel 4.8.6 (I am not using the vanilla kernel because lirc is broken for my device) at the moment.
Kodi 17.0-BETA5-Git:20161028
Youtube addon version 5.2.1

**Comment by jdf76** [comment]
Can you try with the newer version of the plugin. 5.3.4 is available and it supports Dash as long as you install inputstream.mpd.

Jeff

**Comment by andersea** [comment]
I tried version 5.3.2 from the releases page. Not sure where I can find 5.3.4? (typo?)

I don't know how to install inputstream.mpd? From reading https://github.com/peak3d/inputstream.mpd, it seems to be a component of Kodi? Not sure how to update it separately?

The result of updating to 5.3.2 is that now I get a circle on the screen when the video freezes, reading 0%. It stays on 0% and never changes and after a while the video crashes like before and drops out into the menu.

**Comment by jdf76** [comment]
go here and you'll be able to see. I'm in the process of retiring this repo because I have no control over it and the other guy who does own it isn't around anymore.

**Comment by andersea** [comment]
Sorry, go where? There is no link in your post?

**Comment by jdf76** [comment]
it must of stripped it out..

http://forum.kodi.tv/showthread.php?tid=267160

**Comment by andersea** [comment]
Yeah I found it, thanks. I managed to get the inputstream plugin installed from ubuntu packages. It isn't showing up in Kodi yet though, but there are a few things I have yet to try.

Closing this, and if there is anything further I'll check out the forum thread. Thanks again for the help.
