### ISSUE TITLE
Recent content type change reduces view options skin

### ISSUE THREAD

**Issue by RickDB** [Kolifanes/plugin.video.youtube#122]
**Issue**

In a recent commit  ( 542cbfa197d1e9ed14174a060b7f35c63cf4438 ) the content type went from episodes to videos however in Aeon Nox at least this reduces the view options to only list / icons so you see no information only its label.

**Workaround**

Switched content type back to the original `kodion.constants.content_type.EPISODES` in code returns all the view types (low_list/ tri-panel etc..) but not sure if this is the right solution.

**Comment by disrupted** [comment]
yeah, this sucks. also as I believe the manual view override function was removed altogether in this commit. https://github.com/Kolifanes/plugin.video.youtube/commit/6023f7834f9cfd1f09dc3fbb2e47e341d6e9114c

**Comment by RickDB** [comment]
Reverted that locally as well because otherwise if you navigate it would just use the Kodi default for the content type on every "new" page (my subscriptions -> page 1 -> page 2 etc..)

**Comment by disrupted** [comment]
@RickDB yeah, I have no idea why it was removed because it was hidden under advanced settings anyways where it shouldn't confuse the average end user. I think it's time to start a fork.

**Comment by jdf76** [comment]
It was removed from the request of Kodi Developers as they wanted it this way. There is a unofficial version that adds it back in. We'll be doing 2 versions. 1 Official, 1 unofficial. Look in the forum for the link.

**Comment by disrupted** [comment]
@jdf76 alright, thanks for the headsup

**Comment by RickDB** [comment]
Thanks for letting us know :)
Will look it up but for auto-update purposes will their be a repo for the unofficial one?

If the repo is external don't see how the Kodi developers can enforce this then, seems like a bit of an overreach from their end tbh.
Current way is not user friendly as you now can't tell the video information (channel / date etc..) unless you press Info, but understand the decision.

**Comment by disrupted** [comment]
@RickDB I have a [personal repo](https://github.com/disrupted/repo.disrupted/blob/master/repo.disrupted/repo.disrupted-1.0.0.zip?raw=true) where I will push updates of an unofficial version if you're interested, but surely there should be an unofficial repo for everyone to use.

**Comment by jdf76** [comment]
Anxdpanic and I are discussing this.

Don’t worry we’ll have it sorted.

Jeff
