### ISSUE TITLE
Favorites update

### ISSUE THREAD

**Issue by bodyguardroman** [Kolifanes/plugin.video.youtube#2]
when  i added  youtube channel to the favorites , why not update?new videos added to channels not show in favorites...before it worked

**Comment by DjDiabolik** [comment]
Yeah ;) I'm already speak about this problems on official thread on kodi forum :)

On this last days i have supposed to found a workaround (change the favourites.xml and put the username and not a channel ID) but it's not work:
If you put the username and not ChannelID on favourites when you select it you can obtain a result like "search result" and for obtain all video list refresh you need to enter to channel using the "Enter" feature inside context menu......

**Comment by h0d3nt3uf3l** [comment]
Please can you describe the problem further?
Did you mean the favorites from Kodi or Youtube?
What do you do to add a channel to the favorites, where is no autoupdate? Describe your moves in Kodi and try to be as detailed as possible.

**Comment by DjDiabolik** [comment]
It's about kodi favourites........ when you add a channel on kodi favourites and you access on it use the favourites the video present in channel there's no refresh..........

**Comment by h0d3nt3uf3l** [comment]
I've tested it now with Kodiv17 nightly (2015-05-13) and there is no problem. Think this issue is from Kodi itself and they've fixed it already.

**Comment by DjDiabolik** [comment]
Reading here:
http://forum.kodi.tv/showthread.php?tid=267160&pid=2299960#pid2299960

Point 3 issue not fixed...........

**Comment by h0d3nt3uf3l** [comment]
Read here:
http://forum.kodi.tv/showthread.php?tid=238630&pid=2330790#pid2330790
