### ISSUE TITLE
DASH support?

### ISSUE THREAD

**Issue by kq01526** [Kolifanes/plugin.video.youtube#22]
Hi @Kolifanes & @jdf76 ,

according to the following thread on the KODI forums:

http://forum.kodi.tv/showthread.php?tid=237356&pid=2285431#pid2285431

it seems like KODI now supports DASH.

Could you please implement DASH support into the plug-in, so that higher resolutions than 720p and higher framerates than 30 fps will be supported?

Regards

**Comment by kq01526** [comment]
PS:

Okay, looks like DASH support is in Krypton:

http://forum.kodi.tv/showthread.php?tid=237356&pid=2312417#pid2312417

:wink:

@Kolifanes & @jdf76 :

Would be really nice if your plug-in would support DASH with Krypton then :wink:.

Regards

**Comment by nwgat** [comment]
any progress, my 4k tv screams for something better than 720p

**Comment by hasan0097** [comment]
Yes please update!!!

**Comment by kq01526** [comment]
@Kolifanes & @jdf76 ,

Any update on this one?

**Comment by jdf76** [comment]
kolifanes just hosts the site. Dash support is in the latest plugin.

**Comment by jdf76** [comment]
i misunderstood this question are you asking if 1080p+60fps?

**Comment by kq01526** [comment]
> @jdf76 wrote:
> Dash support is in the latest plugin.

Great, so does it now also support higher resolutions than 720p and higher framerates than 30 fps?

> @jdf76 wrote:
> are you asking if 1080p+60fps?

Yes, exactly, we are asking for higher resolutions than 720p and higher framerates than 30 fps.

**Comment by anxdpanic** [comment]
5.3.0 adds dash via inputstream.mpd, which can play >720p. not 100% that it is doing >30fps. Regardless, as it's development goes on we'll only see the benefits.

Also in 5.3.0 If you have a debrid account, urlresolver installed and configured, you could also use that option for >720p again frame rate unknown.

No other options at this moment in Kodi that I'm aware of. Hope that helps.

**Comment by jdf76** [comment]
Closing this issue as it's inputstream related more than youtube plugin related.
