### ISSUE TITLE
Can't authorize new. Help please!

### ISSUE THREAD

**Issue by Titanmarcel** [Kolifanes/plugin.video.youtube#31]
Problem is that I don't see login and logoff button anymore.

They are checked in the settings of the addon.

Can anyone help me?

**Comment by jdf76** [comment]
Please go to the forum @ http://forum.kodi.tv/showthread.php?tid=267160 http://forum.kodi.tv/showthread.php?tid=267160

We will be able to help you there.

Thanks
Jeff (jdf76)
