### ISSUE TITLE
Login fails

### ISSUE THREAD

**Issue by tmetro** [Kolifanes/plugin.video.youtube#35]
I recently updated to your distribution of this plugin (ver 5.2.2), and after activating it worked for about a day and then started failing in the usual ways that are indicative of a login failure. For example, if I go into "My Subscriptions" I get an empty listing.

It always bugged me the way this plugin would encounter login failures and output nothing to the user or the Kodi log, so I started by adding debug logging messages to provider.py and login_client.py. (I'll submit a pull request for this.)

With that done, I could now see the reason why refreshing the access tokens was failing was: anauthorized_client.

According to:
http://stackoverflow.com/questions/13871982/unable-to-refresh-access-token-response-is-unauthorized-client?answertab=votes#tab-top

this happens when you use different client IDs for the auth and refresh calls. So something is confused in the code.

If I repeat the device authorization process, it works again briefly, then fails the same way.

Thoughts?

On a related note, is there a communication channel (email, IRC, forum) to discuss the internals of this plugin? The forum thread for this plugin wouldn't be appropriate for internals, plus I hate giant forum threads in general as s communication channel. They're like a black hole where information goes to die. Too much work to determine what bugs/issues have already been discussed, so everyone asks the same questions repeatedly, making the thread longer, and further burrying the useful info.

**Comment by jdf76** [comment]
To make this easier could you please go to http://forum.kodi.tv/showthread.php?tid=267160 http://forum.kodi.tv/showthread.php?tid=267160 and work on the issue there. 

Also if you could do a debug log and paste the results on pastebin it will probably give us more information.

Thanks
jeff

**Comment by tmetro** [comment]
> To make this easier could you please go to...

Sure, I'll post a copy there, but I don't see how having every possible bug related to a plugin stuck into one giant thread makes it easier on users or developers.

Here you can have each issue in its own ticket, and track the status of that issue as it gets resolved.

Threads are good for triage. Determining whether something might be a bug. Answering "how do I..."

How about developer discussion? You want that mixed into the end-user thread too?

**Comment by h0d3nt3uf3l** [comment]
Jdf76 like it to have all on one spot ;) but sure we can discuss here as well.

I can't recognise how different credentials  would be mixed, because every login is clear seperated in the code. Plz give me a debuglog and your settings.xml.  There I can see the used credentials.

**Comment by h0d3nt3uf3l** [comment]
If there is no more need I'll close this issue.
