### ISSUE TITLE
Regarding google API key issues 

### ISSUE THREAD

**Issue by erimo832** [Kolifanes/plugin.video.youtube#4]
Hi
Great that someone has taken over maintanace of the YouTube addon.
I was looking at how the API keys are handled in the Youtube plugin.
Would it not be a better way to have a list of available API keys. So when a user starts the plugin for the first time it will lock a set of API keys. The selection of what API keys to use should be selected by random.
So if there is a quota issues then it should be an easy fix to add some more API keys to the list.
There is probably some user that already generated an own set of key and want to keep using them. So an option could be to override the random behaviour in the settings-file. So for example if "youtube.api.key", "youtube.api.id", "youtube.api.secret" are all empty then use the random API key selection behaviour. If not use the provided keys from the settings file.

**Comment by jdf76** [comment]
We've made changes to the kodi plugin that should help with that. Please feel free to grab the latest version.

Thank you

Go to the forum if you have any issues.
http://forum.kodi.tv/showthread.php?tid=267160

Thank you ahain!
