### ISSUE TITLE
Cannot connect with YouTube anymore on OpenElec

### ISSUE THREAD

**Issue by EifX** [Kolifanes/plugin.video.youtube#42]
Hi,

I use your plugin on a Raspi 2 with OpenElec and on my Computer with Kodi 15.1 (Ubuntu 16.04). On my Computer, the plugin works well. On my Raspi, I have several issues:

I cannot login with my YouTube-Credentials. If I do that, your plugin returns an error.

The plugin want to login on plugin-launch. Before this error, I saw that I cannot use several "Account-Features" like using my "Liked Videos" or my "Favorites" etc. After I reboot my Raspi, your plugin doesn't want to work ;)

Logs:

> 12:20:07  12.677811 T:1789084736  NOTICE: -->Python Interpreter Initialized<--
> 12:20:09  14.248533 T:1789084736  NOTICE: Previous line repeats 4 times.
> 12:20:09  14.248980 T:1789084736  NOTICE: ## OpenELEC Addon ## 0.6.12
> 12:20:10  15.123634 T:1797473344  NOTICE:  StorageServer Module loaded RUN
> 12:20:10  15.450260 T:1797473344  NOTICE: StorageClient-2.5.4 Starting server
> 12:20:13  17.996212 T:1967992832  NOTICE: UDev: Added /var/media/EIFX_KODI
> 12:20:24  29.024082 T:1609561152  NOTICE: Thread LanguageInvoker start, auto delete: false
> 12:20:24  29.176170 T:1609561152  NOTICE: -->Python Interpreter Initialized<--
> 12:20:24  29.839001 T:1609561152  NOTICE: [plugin.video.youtube] Running: YouTube (5.2.1) on Isengard (15.2) with Python 2.7.3
> 12:21:23  88.435593 T:1670321216  NOTICE: ES: Client  from 192.168.0.101 timed out
> 12:21:26  91.649979 T:1609561152   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.IndexError'>
>                                             Error Contents: string index out of range
>                                             Traceback (most recent call last):
>                                               File "/storage/.kodi/addons/plugin.video.youtube/default.py", line 7, in <module>
>                                                 runner.run(**provider**)
>                                               File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/kodion/runner.py", line 32, in run
>                                                 **RUNNER**.run(provider, context)
>                                               File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/kodion/impl/xbmc/xbmc_runner.py", line 23, in run
>                                                 results = provider.navigate(context)
>                                               File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/kodion/abstract_provider.py", line 123, in navigate
>                                                 result = method(context, re_match)
>                                               File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/kodion/abstract_provider.py", line 157, in _internal_root
>                                                 return self.on_root(context, re_match)
>                                               File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube/provider.py", line 500, in on_root
>                                                 yt_login.process(mode, self, context, re_match, False)
>                                               File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube/helper/yt_login.py", line 123, in process
>                                                 access_token = '%s|%s' % (access_tokens[0], access_token_kodi)
>                                             IndexError: string index out of range
>                                             -->End of Python script error report<--
> 12:21:26  91.663521 T:1947202624  NOTICE: CAESinkPi:AddPackets Underrun (delay:0.00 frames:2205)
> 12:21:26  91.801720 T:1967992832   ERROR: GetDirectory - Error getting plugin://plugin.video.youtube/
> 12:21:26  91.804207 T:1967992832   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/) failed
> 12:21:26  91.831352 T:1609561152  NOTICE: Thread BackgroundLoader start, auto delete: false
> 12:21:38 102.882927 T:1609561152  NOTICE: Thread LanguageInvoker start, auto delete: false
> 12:21:38 102.906731 T:1967992832   ERROR: Control 50 in window 10025 has been asked to focus, but it can't

**Comment by jdf76** [comment]
try deleting 

/storage/.kodi/userdata/addon_data/plugin.video.youtube

and when you restart youtube it should start the whole set up process over.

Jeff

**Comment by EifX** [comment]
Oh... Thx for your fast answer! This works for me :)
