### ISSUE TITLE
Unknown kind '' error

### ISSUE THREAD

**Issue by EifX** [Kolifanes/plugin.video.youtube#44]
Hi,

I have a problem with your plugin on my Raspberry Pi 2 with OpenElec 6.0.3. It's a very mysterious error and I hope I describe it well.

The plugin was installed cleanly (no folder 'plugin.video.youtube' in addon_data). I log me in with the youtube.com/activate-thing. The plugin works very well.
Someday (I cannot reproduce when), I get an error-message, when I want to watch my subscriptions:

Exception in ContentProvider: Unknown kind ''

Here the log-entry:

> 08:07:14  31.521519 T:1574437952  NOTICE: -->Python Interpreter Initialized<--
> 08:07:15  32.042309 T:1574437952  NOTICE: [plugin.video.youtube] Running: YouTube (5.2.1) on Isengard (15.2) with Python 2.7.3
> 08:07:15  32.189186 T:1574437952   ERROR: [plugin.video.youtube] Unknown kind ''
> 08:07:28  44.929531 T:1967505408   ERROR: GetDirectory - Error getting plugin://plugin.video.youtube/subscriptions/list/
> 08:07:28  44.931992 T:1967505408   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/subscriptions/list/) failed
> 08:07:28  44.947025 T:1574437952  NOTICE: Thread BackgroundLoader start, auto delete: false
> 08:07:29  45.714966 T:1574437952  NOTICE: Thread LanguageInvoker start, auto delete: false

If this error-message appear, I try it a few times again and suddenly it works... After this message, this exception doesn't appear again.

If I close the plugin and want to use it again, the same message appears again. Now, I have to try it a few times more (more then the first time) and it suddenly works...

If I retry this scenario again, it's now unpossible to skip this error message by try it again and again. If I restart the Rasperry Pi, I have the problem, which I described in Issue #42 

After I deleted the addon_data-files, I can use the plugin again.

**Comment by jdf76** [comment]
Hello.

The "Exception in ContentProvider: Unknown kind ‘’” and the “Quota exceeded” issue is a well known and documented API usage issue with Youtube itself. Please visit http://forum.kodi.tv/showthread.php?tid=267160 to get some help with that.

Thanks
Jeff

**Comment by EifX** [comment]
Hi,

thanks for this answer. Hmm, that's really a problem with the quota-thingy.

This error-message appears only on my raspberry pi, but not on my laptop (Kodi 15.2 / Ubuntu 16.04). Can you explain me the difference?

It's ok for me, if youtube don't work for a day or so. It's irritating for me, that my login-credentials will be missed after this problem appears. I have to reset the whole installation. Can you improve this?

**Comment by jdf76** [comment]
Raspberry Pi uses OpenElec or some variant. Their version is probably different reported to youtube plugin. The API codes are different per each version of kodi.

Honestly if you want to control your own Youtube API calls, set up that API key 

Here is the link to get the instructions.

http://forum.kodi.tv/showthread.php?tid=267160&pid=2299963#pid2299963

Jeff

**Comment by EifX** [comment]
Ok, thanks! Maybe a notice or something in the Readme.md helps to point on this solution. :wink:
