### ISSUE TITLE
[Feature Request] Add Connect to Kodi via App

### ISSUE THREAD

**Issue by avjui** [Kolifanes/plugin.video.youtube#51]
First thank for development

Is there any plan to add the "Connect" function. All the smart tv´s are able to handle this, so it will be great to add this function also to your addon.

**Comment by h0d3nt3uf3l** [comment]
As far as I know the API for this section is not public. So sadly there is no option to handle it. If you found the part of the API and how to use it we can talk about it. Would appreciate this function too :)
