### ISSUE TITLE
Crash with Kodi v17

### ISSUE THREAD

**Issue by Spidored** [Kolifanes/plugin.video.youtube#6]
When opening the Youtube ext on Kodi v17 (Build of 2016-03-19) with the new Estuary skin, the app crash completely.

Here is the crash log : 
http://pastebin.com/fLBkjMUp

**Comment by h0d3nt3uf3l** [comment]
Can't confirm this. I have installed the same Build (over my Kodi v16) and tried it without any issues.
I use Windows7 to test. Can you rebuild the error? What do you have done befor? I'm sorry but I don't get smarter because of the log.
