### ISSUE TITLE
Does not work with kodi 16.1 and python 2.7.12+

### ISSUE THREAD

**Issue by noccio** [Kolifanes/plugin.video.youtube#69]
I have this trouble on a Debian Squeeze/testing with kodi (16.1) and python (2.7.11-2) coming from testing. This is the error log:

> 09:53:03 T:140200651253504  NOTICE: [plugin.video.youtube] Running: YouTube (5.2.2) on Jarvis (16.1) with Python 2.7.12+
> 09:53:11 T:140200651253504  NOTICE: Previous line repeats 1 times.
> 09:53:11 T:140200651253504   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <class 'urllib2.URLError'>
>                                             Error Contents: <urlopen error [Errno 0] Error>
>                                             Traceback (most recent call last):
>                                               File "/home/pinolino/.kodi/addons/plugin.video.youtube/default.py", line 7, in <module>
>                                                 runner.run(**provider**)
>                                               File "/home/pinolino/.kodi/addons/plugin.video.youtube/resources/lib/kodion/runner.py", line 32, in run
>                                                 **RUNNER**.run(provider, context)
>                                               File "/home/pinolino/.kodi/addons/plugin.video.youtube/resources/lib/kodion/impl/xbmc/xbmc_runner.py", line 23, in run
>                                                 results = provider.navigate(context)
>                                               File "/home/pinolino/.kodi/addons/plugin.video.youtube/resources/lib/kodion/abstract_provider.py", line 123, in navigate
>                                                 result = method(context, re_match)
>                                               File "/home/pinolino/.kodi/addons/plugin.video.youtube/resources/lib/kodion/abstract_provider.py", line 255, in _internal_search
>                                                 return self.on_search(query, context, re_match)
>                                               File "/home/pinolino/.kodi/addons/plugin.video.youtube/resources/lib/youtube/provider.py", line 477, in on_search
>                                                 page_token=page_token)
>                                               File "/home/pinolino/.kodi/addons/plugin.video.youtube/resources/lib/kodion/utils/function_cache.py", line 107, in get
>                                                 cached_data = partial_func()
>                                               File "/home/pinolino/.kodi/addons/plugin.video.youtube/resources/lib/youtube/client/youtube.py", line 488, in search
>                                                 return self._perform_v3_request(method='GET', path='search', params=params, quota_optimized=False)
>                                               File "/home/pinolino/.kodi/addons/plugin.video.youtube/resources/lib/youtube/client/youtube.py", line 615, in _perform_v3_request
>                                                 result = requests.get(_url, params=_params, headers=_headers, verify=False, allow_redirects=allow_redirects)
>                                               File "/home/pinolino/.kodi/addons/plugin.video.youtube/resources/lib/kodion/simple_requests/api.py", line 179, in get
>                                                 return _request('GET', url, *_kwargs)
>                                               File "/home/pinolino/.kodi/addons/plugin.video.youtube/resources/lib/kodion/simple_requests/api.py", line 155, in _request
>                                                 response = opener.open(request)
>                                               File "/usr/lib/python2.7/urllib2.py", line 429, in open
>                                                 response = self._open(req, data)
>                                               File "/usr/lib/python2.7/urllib2.py", line 447, in _open
>                                                 '_open', req)
>                                               File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
>                                                 result = func(_args)
>                                               File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
>                                                 context=self._context)
>                                               File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
>                                                 raise URLError(err)
>                                             URLError: <urlopen error [Errno 0] Error>
>                                             -->End of Python script error report<--
> 09:53:11 T:140201815980928   ERROR: GetDirectory - Error getting plugin://plugin.video.youtube/kodion/search/query/?q=cosmo%20le%20voci
> 09:53:11 T:140201815980928   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/kodion/search/query/?q=cosmo%20le%20voci) failed

What is wrong?

**Comment by X-dark** [comment]
I think this is a duplicate of #60

**Comment by noccio** [comment]
Yes, I think the same so I will close this report
