### ISSUE TITLE
Removing playlist items causes "Playlist item not found" error

### ISSUE THREAD

**Issue by NaLogo** [Kolifanes/plugin.video.youtube#7]
Deleting an item from a playlist or having the plugin auto-remove titles from "Watch Later" will cause a "Playlist item not found" error.

I don't think it produces any errors or warnings in the Kodi log. The only entry that sticks out is "Attempt to use invalid handle -1" but that may have no connection to that issue.

Neither re-installing the plugin nor re-authenticating fixed the issue for me. Maybe the API changed?

**Comment by ddwagnz** [comment]
Might be a API change as ive started getting this too

**Comment by philippbeckmann** [comment]
Seems like a problem with the api: https://code.google.com/p/gdata-issues/issues/detail?id=8145

**Comment by disrupted** [comment]
hopefully Google gets their shit together soon
