### ISSUE TITLE
Watch later playlist empty

### ISSUE THREAD

**Issue by vaisov** [Kolifanes/plugin.video.youtube#71]
Hi,

using your plugin on OSMC.tv (runs on Kodi) I get empty "Watch later" playlist. I tried to re-login, but it's still empty. Other playlists are ok though.

**Comment by ddwagnz** [comment]
This is because of a API change on google's end https://developers.google.com/youtube/v3/revision_history

**Comment by disrupted** [comment]
in this case it should be removed from the addon imo until it is possible again

**Comment by jdf76** [comment]
I doublt youtube is going to re-add it. They'd rather have you use they youtube-tv app. We did write a work around for kodi. I basically created another playlist and stores all that stuff there, but it only works for kodi.

**Comment by disrupted** [comment]
might be interesting to know how other 3rd party developers access it. for instance it works in myTube for Windows

**Comment by jdf76** [comment]
Mytube doesn't look to be open source so i don't think they would just hand the code over, but feel free to fork the project and give it a shot. We'd be happy to take any one who would like to contribute their code to the project and they get full credit of course.
